export interface Product {
  id: string
  title: string
  category: string
  filterCategory: string
  desc: string
  img: string
  features: string[]
  tech: string[]
  playstore: string
  privacyPolicy?: string
}

export const products: Product[] = [
  {
    id: '1',
    title: 'Walkmates',
    category: 'Health & Fitness',
    filterCategory: 'apps',
    desc: 'A community-driven walking app that transforms everyday steps into shared adventures. Set goals, join group challenges, and track your journey with friends in real time.',
    img: '/image/walkmates.png',
    features: ['GPS Route Tracking', 'Community Challenges', 'Step & Calorie Counter', 'Friend Leaderboards'],
    tech: ['React Native', 'Google Health Connect', 'Apple HealthKit', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
  },
  {
    id: '2',
    title: 'Artify: AR Trace & Sketch',
    category: 'AR / Creative',
    filterCategory: 'creative apps',
    desc: 'An AR-powered creative studio that lets you project and trace real-world objects onto your canvas, then refine them into polished digital illustrations with professional sketch tools.',
    img: '/image/artify.png',
    features: ['AR Object Projection', 'Layered Sketch Canvas', 'Export to PNG / SVG', 'Real-time Brush Engine'],
    tech: ['React Native', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/details?id=com.appaxislab.artify.draw.trace.sketch',
    privacyPolicy: '/artify_privacy',
  },
  {
    id: '3',
    title: 'Ismart Translator',
    category: 'Productivity',
    filterCategory: 'utilities apps',
    desc: 'Instant voice and text translation across 100+ languages. Features offline mode, camera OCR for sign and document translation, and conversation mode for two-way real-time dialogue.',
    img: '/image/ismart.png',
    features: ['100+ Language Support', 'Voice & Camera Translation', 'Offline Mode', 'Conversation Mode'],
    tech: ['React Native', 'Kotlin'],
    playstore: 'https://play.google.com/store/apps/details?id=com.appaxislab.translyapp',
    privacyPolicy: '/ismarttranslator_privacy',
  },
  {
    id: '4',
    title: 'All Document Reader: AI & Docs',
    category: 'Productivity',
    filterCategory: 'utilities apps',
    desc: 'A universal document reader that handles every major file format — PDF, Word, Excel, PowerPoint, and more — with AI-powered summarization, smart search, and annotation tools built in.',
    img: '/image/docreader.png',
    features: ['All Format Support (PDF, DOCX, XLSX, PPT)', 'AI Document Summarization', 'Smart Search & Annotations', 'Cloud & Local File Access'],
    tech: ['React Native', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/details?id=com.appaxislab.pdf.reader.ai.summary',
    privacyPolicy: '/pdfreader_privacy',
  },
  {
    id: '5',
    title: 'Wallpaper App',
    category: 'Lifestyle',
    filterCategory: 'apps',
    desc: 'A curated wallpaper platform with thousands of high-quality backgrounds. Browse community uploads, save your favorites, and share your own creations with a thriving visual community.',
    img: '/image/logo.png',
    features: ['Curated HD Wallpaper Library', 'Community Uploads & Sharing', 'Favorites Sync Across Devices', 'Google & Apple Sign-In'],
    tech: ['React Native', 'Firebase', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/wallpaper_privacy',
  },
  {
    id: '6',
    title: 'AI Phone Storage Cleaner',
    category: 'Utilities',
    filterCategory: 'utilities',
    desc: 'A smart storage optimizer that scans your device for junk files, large files, and unused apps — freeing up space and boosting performance with one tap.',
    img: '/image/logo.png',
    features: ['Junk & Cache File Cleaner', 'Large File Scanner', 'Unused App Detector', 'Real-time Storage Analysis'],
    tech: ['Kotlin', 'Android SDK', 'Firebase'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/phonecleaner_privacy',
  },
  {
    id: '7',
    title: 'Settlo',
    category: 'Finance',
    filterCategory: 'apps',
    desc: 'A shared expense management app that makes splitting bills effortless. Track group expenses, settle debts, and keep everyone on the same page — for trips, households, and more.',
    img: '/image/logo.png',
    features: ['Group Expense Tracking', 'Smart Bill Splitting', 'Debt Settlement Reminders', 'Expense History & Reports'],
    tech: ['React Native', 'Firebase', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/settlo_privacy_policy',
  },
  {
    id: '8',
    title: 'AxisFlow Period Tracker',
    category: 'Health & Fitness',
    filterCategory: 'apps',
    desc: 'A private, AI-assisted period and cycle tracker that helps you understand your body. Log symptoms, predict cycles, and get personalized health insights — all stored securely on-device.',
    img: '/image/logo.png',
    features: ['Cycle Prediction & Tracking', 'Symptom & Mood Logging', 'AI Health Insights', 'On-Device Private Storage'],
    tech: ['React Native', 'Apple HealthKit', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/periodtracker-policy',
  },
  {
    id: '9',
    title: 'Habbit Tracker',
    category: 'Productivity',
    filterCategory: 'apps',
    desc: 'A powerful habit-building app that transforms daily routines into lasting change. Track streaks, follow expert-designed journeys, unlock achievements, and gain deep insights into your progress.',
    img: '/image/logo.png',
    features: ['Streak & Achievement System', 'Expert Habit Journeys', 'Local-First Private Storage', 'Analytics & Progress Reports'],
    tech: ['React Native', 'Realm', 'Firebase', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/habbit_tracker_privacy',
  },
  {
    id: '10',
    title: 'HireX AI',
    category: 'Productivity',
    filterCategory: 'apps',
    desc: 'An AI-powered resume builder that helps you create, edit, and export professional resumes using customizable templates and AI-generated summaries and skill suggestions.',
    img: '/image/logo.png',
    features: ['AI-Powered Resume Suggestions', 'Customizable Resume Templates', 'PDF Merge, Split & Export Tools', 'Secure Cloud Sync'],
    tech: ['React Native', 'Supabase', 'OpenAI', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/hirex_ai_privacy',
  },
  {
    id: '11',
    title: 'AI Notes Taker',
    category: 'Productivity',
    filterCategory: 'apps',
    desc: 'A voice-to-text note-taking app that records audio memos and turns them into accurate transcripts and smart AI-generated summaries, synced securely across all your devices.',
    img: '/image/logo.png',
    features: ['AI Voice Transcription', 'Smart AI Summaries', 'Cross-Device Sync', 'PDF, Image & Video Text Extraction'],
    tech: ['React Native', 'Supabase', 'OpenAI', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/ainotestaker_privacy',
  },
  {
    id: '12',
    title: 'Sanctuary: Voice Journal AI',
    category: 'Health & Wellness',
    filterCategory: 'apps',
    desc: 'A private, voice-journaling app with no account required. Speak your thoughts, get AI-powered mood insights and reflections, and keep everything encrypted and on-device — your journal is yours alone.',
    img: '/image/logo.png',
    features: ['No Account, Fully Anonymous', 'On-Device Voice Journaling', 'AI Mood Insights & Reflections', 'Encrypted Optional Backup'],
    tech: ['React Native', 'OpenAI API', 'Firebase', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/sanctuary_privacy',
  },
  {
    id: '13',
    title: 'Studio Recorder',
    category: 'Utilities',
    filterCategory: 'utilities apps',
    desc: 'An on-device screen recorder with face-cam overlay, watermarks, and a floating control button. Recordings and screenshots stay private on your device — no account and no cloud upload required.',
    img: '/image/logo.png',
    features: ['HD Screen Recording', 'Face-Cam & Watermark Overlay', 'Floating Control Button', 'On-Device Privacy, No Account Needed'],
    tech: ['Kotlin', 'Android SDK', 'Firebase', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/studio_recorder_privacy',
  },
  {
    id: '14',
    title: 'Settly',
    category: 'Finance',
    filterCategory: 'apps',
    desc: 'A debt and personal-finance management app that helps you track money you owe and are owed, log transactions, organize contacts, and stay on top of budgets — synced securely across your devices.',
    img: '/image/logo.png',
    features: ['Debt & Loan Tracking', 'Budgets & Recurring Entries', 'Contact-Linked Records', 'PIN & Biometric Lock'],
    tech: ['React Native', 'Supabase', 'RevenueCat', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/settly_privacy_policy',
  },
  {
    id: '15',
    title: 'Privacy Shield',
    category: 'Utilities',
    filterCategory: 'utilities apps',
    desc: 'A visual privacy overlay that draws a directional gradient over your screen, keeping content readable face-on while shielding it from side-angle glances. No account, no ads, no data leaves your device.',
    img: '/image/logo.png',
    features: ['Directional Gradient Overlay', 'Gyroscope-Based Angle Detection', 'Scheduled Auto Activation', 'Fully On-Device, No Account'],
    tech: ['Kotlin', 'Android SDK', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/privacy_shield_privacy',
  },
  {
    id: '16',
    title: 'VoiceFunk',
    category: 'Entertainment',
    filterCategory: 'creative apps',
    desc: 'A voice changer and audio/video effects app that lets you record, transform, and share your voice with fun effects — plus handy audio tools like noise reduction, trim, mix, and speech-to-text, all processed on-device.',
    img: '/image/logo.png',
    features: ['Voice & Video Effects', 'Noise Reduction & Audio Trim/Mix', 'Speech-to-Text Transcription', 'On-Device Processing, No Account Needed'],
    tech: ['Kotlin', 'Android SDK', 'Firebase'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/voicefunk_privacy',
  },
  {
    id: '17',
    title: 'Live Microphone',
    category: 'Utilities',
    filterCategory: 'utilities apps',
    desc: 'An offline audio toolkit with hands-free push-to-talk recording, a manual voice recorder, on-device text-to-speech, voice effects, and a live microphone-to-speaker passthrough — no account, no cloud, everything stays on your device.',
    img: '/image/logo.png',
    features: ['Hold & Speak Push-to-Talk Recording', 'Text to Audio with OCR & PDF Import', 'On-Device Voice Effects', 'Live Mic Passthrough, No Account Needed'],
    tech: ['Kotlin', 'Android SDK', 'FFmpeg'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/live_microphone_privacy',
  },
  {
    id: '18',
    title: 'WakeForge',
    category: 'Productivity',
    filterCategory: 'apps',
    desc: 'A mission-based alarm clock that makes waking up a challenge to beat. Complete missions to silence your alarm, build streaks, and stay accountable with friends and shared alarms.',
    img: '/image/logo.png',
    features: ['Mission-Based Alarm Challenges', 'Anonymous Account, No Sign-Up', 'Friends, Groups & Shared Alarms', 'Streaks & Win Statistics'],
    tech: ['Supabase', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/wakeforge_privacy',
  },
  {
    id: '19',
    title: 'Family Location Tracker',
    category: 'Family & Safety',
    filterCategory: 'apps',
    desc: 'A family safety and location-sharing app built around private circles. See real-time location and battery status, set up geofence alerts, send an SOS in an emergency, and remotely ring a family member\'s phone to help them find it.',
    img: '/image/logo.png',
    features: ['Real-Time Circle Location Sharing', 'Geofence & Battery Alerts', 'One-Tap SOS Emergency Alerts', 'Remote Ring-My-Device'],
    tech: ['React Native', 'Supabase', 'RevenueCat', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/family_location_tracker_privacy',
  },
  {
    id: '20',
    title: 'My Diabetic Health',
    category: 'Health & Fitness',
    filterCategory: 'apps',
    desc: 'A privacy-first glucose and blood pressure tracker that helps you log readings, medications, meals, and insulin doses, and generate doctor-ready reports — with all health data encrypted and stored locally on your device.',
    img: '/image/logo.png',
    features: ['Glucose & Blood Pressure Tracking', 'On-Device AES-256 Encryption', 'Biometric-Locked Health Vault', 'Doctor Report PDF Export'],
    tech: ['Kotlin', 'Android SDK', 'SQLCipher', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/my_diabetic_health_privacy',
  },
  {
    id: '21',
    title: 'AxisCast',
    category: 'Utilities',
    filterCategory: 'utilities apps',
    desc: 'A screen mirroring and casting app that streams your phone’s screen directly to nearby computers, TVs, and other screens over your local Wi-Fi — no account, no cloud server, fully peer-to-peer.',
    img: '/image/logo.png',
    features: ['Peer-to-Peer Screen Mirroring', 'QR / PIN Device Pairing', 'No Account, Fully Anonymous', 'Encrypted Local Wi-Fi Streaming'],
    tech: ['Kotlin', 'Android SDK', 'WebRTC', 'Firebase', 'RevenueCat'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/axiscast_privacy',
  },
  {
    id: '22',
    title: 'Teleprompter',
    category: 'Productivity',
    filterCategory: 'apps',
    desc: 'A script reader and video recorder that auto-scrolls your script as you read it on camera, including hands-free voice-driven scrolling, then lets you trim, caption, and style the recording in a built-in video editor.',
    img: '/image/logo.png',
    features: ['Voice-Driven Auto-Scroll Teleprompter', 'On-Device Video Editor & Captions', 'AI Script Writer (Bring-Your-Own-Key)', 'No Account, Fully Local-First'],
    tech: ['React Native', 'OpenAI API', 'Anthropic API', 'Kotlin', 'Swift'],
    playstore: 'https://play.google.com/store/apps/developer?id=App+Axis+Lab',
    privacyPolicy: '/teleprompter_privacy',
  },
]
